plugins {
    id 'maven-publish'
}

group = 'co.yaqut.reader'
version = '1.6.8' // Set the version for your library

publishing {
    publications {
        aar(MavenPublication) {
            groupId = project.group
            artifactId = 'reader'
            version = project.version

            artifact(file('app-release.aar')) {
                extension 'aar'
            }
        }
    }

    repositories {
        mavenLocal() // Publishes to ~/.m2/repository
    }
}